'use client';

import { Amplify } from 'aws-amplify';
// import outputs from '@/../amplify_outputs.json';
// Note: outputs will be generated by amplify sandbox, for now we just prepare the config

export function ConfigureAmplifyClientSide() {
  // if (typeof window !== 'undefined') {
  //   Amplify.configure(outputs);
  // }
  return null;
}
